export const products = [
  // ================= ELECTRONICS =================
  {
    name: "Samsung Galaxy S23 Ultra",
    price: 1299,
    description: "Flagship smartphone with 200MP camera and Snapdragon processor.",
    images: [{ public_id: "s23_ultra", url: "https://example.com/s23.jpg" }],
    category: "Electronics",
    seller: "Samsung",
    stock: 30,
    rating: 4.8,
    numOfReviews: 220,
  },
  {
    name: "Apple Watch Series 9",
    price: 499,
    description: "Advanced smartwatch with health tracking and Always-On display.",
    images: [{ public_id: "watch9", url: "https://example.com/watch.jpg" }],
    category: "Electronics",
    seller: "Apple",
    stock: 45,
    rating: 4.7,
    numOfReviews: 180,
  },

  // ================= CAMERAS =================
  {
    name: "Canon EOS R6",
    price: 2499,
    description: "Professional mirrorless camera with fast autofocus.",
    images: [{ public_id: "canon_r6", url: "https://example.com/r6.jpg" }],
    category: "Cameras",
    seller: "Canon",
    stock: 12,
    rating: 4.6,
    numOfReviews: 76,
  },
  {
    name: "GoPro HERO 11",
    price: 399,
    description: "Action camera with 5.3K video and HyperSmooth stabilization.",
    images: [{ public_id: "gopro11", url: "https://example.com/gopro.jpg" }],
    category: "Cameras",
    seller: "GoPro",
    stock: 50,
    rating: 4.5,
    numOfReviews: 143,
  },

  // ================= LAPTOPS =================
  {
    name: "MacBook Pro 16 M2",
    price: 2799,
    description: "Powerful laptop with Apple M2 chip for professionals.",
    images: [{ public_id: "mbp16", url: "https://example.com/mbp.jpg" }],
    category: "Laptops",
    seller: "Apple",
    stock: 8,
    rating: 4.9,
    numOfReviews: 95,
  },
  {
    name: "HP Spectre x360",
    price: 1599,
    description: "Convertible laptop with OLED display and sleek design.",
    images: [{ public_id: "spectre", url: "https://example.com/spectre.jpg" }],
    category: "Laptops",
    seller: "HP",
    stock: 14,
    rating: 4.4,
    numOfReviews: 58,
  },

  // ================= ACCESSORIES =================
  {
    name: "USB-C Fast Charging Cable",
    price: 19,
    description: "Durable fast-charging USB-C cable.",
    images: [{ public_id: "usbc", url: "https://example.com/cable.jpg" }],
    category: "Accessories",
    seller: "Anker",
    stock: 150,
    rating: 4.3,
    numOfReviews: 340,
  },
  {
    name: "Laptop Backpack",
    price: 79,
    description: "Water-resistant backpack with laptop compartment.",
    images: [{ public_id: "backpack", url: "https://example.com/bag.jpg" }],
    category: "Accessories",
    seller: "Samsonite",
    stock: 65,
    rating: 4.4,
    numOfReviews: 88,
  },

  // ================= HEADPHONES =================
  {
    name: "Sony WH-1000XM5",
    price: 399,
    description: "Industry-leading noise canceling headphones.",
    images: [{ public_id: "sony_xm5", url: "https://example.com/xm5.jpg" }],
    category: "Headphones",
    seller: "Sony",
    stock: 35,
    rating: 4.9,
    numOfReviews: 410,
  },
  {
    name: "AirPods Pro 2",
    price: 249,
    description: "Wireless earbuds with spatial audio.",
    images: [{ public_id: "airpods", url: "https://example.com/airpods.jpg" }],
    category: "Headphones",
    seller: "Apple",
    stock: 70,
    rating: 4.7,
    numOfReviews: 520,
  },

  // ================= FOOD =================
  {
    name: "Organic Honey 1kg",
    price: 15,
    description: "Pure organic honey sourced from wildflowers.",
    images: [{ public_id: "honey", url: "https://example.com/honey.jpg" }],
    category: "Food",
    seller: "Nature Farm",
    stock: 100,
    rating: 4.6,
    numOfReviews: 64,
  },
  {
    name: "Premium Arabica Coffee Beans",
    price: 22,
    description: "Freshly roasted premium coffee beans.",
    images: [{ public_id: "coffee", url: "https://example.com/coffee.jpg" }],
    category: "Food",
    seller: "Coffee Roasters",
    stock: 80,
    rating: 4.8,
    numOfReviews: 112,
  },

  // ================= BOOKS =================
  {
    name: "Atomic Habits",
    price: 18,
    description: "Bestselling book on habit building.",
    images: [{ public_id: "atomic", url: "https://example.com/book1.jpg" }],
    category: "Books",
    seller: "Penguin",
    stock: 120,
    rating: 4.9,
    numOfReviews: 980,
  },
  {
    name: "Clean Code",
    price: 35,
    description: "A handbook of agile software craftsmanship.",
    images: [{ public_id: "cleancode", url: "https://example.com/book2.jpg" }],
    category: "Books",
    seller: "Prentice Hall",
    stock: 60,
    rating: 4.7,
    numOfReviews: 410,
  },

  // ================= CLOTHES / SHOES =================
  {
    name: "Men's Denim Jacket",
    price: 99,
    description: "Classic fit denim jacket.",
    images: [{ public_id: "jacket", url: "https://example.com/jacket.jpg" }],
    category: "Clothes/Shoes",
    seller: "Levi's",
    stock: 40,
    rating: 4.4,
    numOfReviews: 73,
  },
  {
    name: "Women's Running Shoes",
    price: 130,
    description: "Comfortable and lightweight running shoes.",
    images: [{ public_id: "shoes", url: "https://example.com/shoes.jpg" }],
    category: "Clothes/Shoes",
    seller: "Adidas",
    stock: 55,
    rating: 4.6,
    numOfReviews: 190,
  },

  // ================= BEAUTY / HEALTH =================
  {
    name: "Vitamin C Serum",
    price: 29,
    description: "Brightening facial serum with Vitamin C.",
    images: [{ public_id: "serum", url: "https://example.com/serum.jpg" }],
    category: "Beauty/Health",
    seller: "The Ordinary",
    stock: 90,
    rating: 4.5,
    numOfReviews: 210,
  },
  {
    name: "Electric Toothbrush",
    price: 89,
    description: "Rechargeable toothbrush with multiple modes.",
    images: [{ public_id: "toothbrush", url: "https://example.com/toothbrush.jpg" }],
    category: "Beauty/Health",
    seller: "Philips",
    stock: 70,
    rating: 4.6,
    numOfReviews: 155,
  },

  // ================= SPORTS =================
  {
    name: "Professional Football",
    price: 45,
    description: "FIFA-approved professional football.",
    images: [{ public_id: "football", url: "https://example.com/football.jpg" }],
    category: "Sports",
    seller: "Adidas",
    stock: 85,
    rating: 4.7,
    numOfReviews: 132,
  },
  {
    name: "Adjustable Dumbbell Set",
    price: 299,
    description: "All-in-one dumbbell set for home workouts.",
    images: [{ public_id: "dumbbell", url: "https://example.com/dumbbell.jpg" }],
    category: "Sports",
    seller: "Bowflex",
    stock: 25,
    rating: 4.8,
    numOfReviews: 94,
  },

  // ================= OUTDOOR =================
  {
    name: "Camping Tent (4 Person)",
    price: 199,
    description: "Waterproof camping tent with easy setup.",
    images: [{ public_id: "tent", url: "https://example.com/tent.jpg" }],
    category: "Outdoor",
    seller: "Coleman",
    stock: 30,
    rating: 4.5,
    numOfReviews: 61,
  },
  {
    name: "Hiking Backpack 60L",
    price: 149,
    description: "Large capacity backpack for long hikes.",
    images: [{ public_id: "hiking_bag", url: "https://example.com/hikingbag.jpg" }],
    category: "Outdoor",
    seller: "Osprey",
    stock: 22,
    rating: 4.7,
    numOfReviews: 84,
  },

  // ================= HOME =================
  {
    name: "Air Purifier",
    price: 179,
    description: "HEPA air purifier for clean indoor air.",
    images: [{ public_id: "air_purifier", url: "https://example.com/air.jpg" }],
    category: "Home",
    seller: "Xiaomi",
    stock: 40,
    rating: 4.6,
    numOfReviews: 118,
  },
  {
    name: "Non-Stick Cookware Set",
    price: 249,
    description: "10-piece non-stick cookware set.",
    images: [{ public_id: "cookware", url: "https://example.com/cookware.jpg" }],
    category: "Home",
    seller: "Tefal",
    stock: 35,
    rating: 4.5,
    numOfReviews: 90,
  }
];
